### ISSUE TITLE
Detect ensemble changes in order to update configmaps / restart pods with new configuration

### ISSUE THREAD

**Issue by maltesander** [stackabletech/zookeeper-operator#128]
The ZooKeeper config file (zoo.cfg) requires to list all servers, their respective ids and host names like:
```
server.1=some_host_name_and_port
server.2=some_other_host_name_and_port
```

Currently we do not react on changes (e.g. pod crash or up/down scaling) regarding the config maps.
Whenever something changes in the cluster, configmaps need to be updated (and pods need to be restarted for now).

There is a similar case in spark where workers need to know all available masters when started. There we have a label with a hash of all available master urls (in the worker pods) and check that hash every reconcile and restart that pod with the updated configuration if the hash does not match. 

This would be an option here as well.

This issue is already covered in the [zookeeper-operator-integration-tests](https://github.com/stackabletech/zookeeper-operator-integration-tests) (as of now in the "start" branch) and can be tested.

**Comment by lfrancke** [comment]
This will be handled by the operator rework
