### ISSUE TITLE
Enable deployment of basic hybrid clusters

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/zookeeper-operator#148]
The workloads that are deployed by Stackable (Apache Kafka, Apache HDFS, ...) do not necessarily care that much whether they are deployed on bare metal or in a container within Kubernetes.

Up until now all our efforts have been geared towards running these workloads on bare-metal with systemd, while always keeping "real" Kubernetes in the back of our minds.

This epic will serve to track an initial spike to get Kafka & Zookeeper ready for hybrid deployments.

**Comment by lfrancke** [comment]
Moving to k8s only for now, closing this
