### ISSUE TITLE
Enable simple TLS authentication

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/zookeeper-operator#25]
This is for Client-Server communication

**Acceptance Criteria**

- [ ] Operator has a canonical place where it looks up the keys
- [ ] ZK authentication can be turned on/off via the ZK CRDs The default authn method is client TLS certificates.
- [ ] When an agent presents a valid client TLS certificate, it is authenticated with ZK.
- [ ] When an agent does not present a valid client TLS certificate or the certificate or owner is unkown to ZK, the user is blocked from accessing ZK (unless authn is turned of)

**Comment by soenkeliebau** [comment]
Left in release 2 with the assumption that keys and certificates are provided and we _only_ need to configure them in the ZK config.

**Comment by soenkeliebau** [comment]
possible duplicate of: https://github.com/stackabletech/issues/issues/108

**Comment by maltesander** [comment]
@lfrancke this was done in https://github.com/stackabletech/zookeeper-operator/pull/479 but referenced another issue...
Can we close this?
Quorum is always authenticated, client/agent can be encrypted and/or authenticated via crd settings.

**Comment by lfrancke** [comment]
I believe we can! Thank you
