### ISSUE TITLE
envOverrides in config-spec doesn't override environment variables set by the operator

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/zookeeper-operator#272]
When setting env vars in the config spec for ZooKeeper using envOverrides, new env vars can be set but you cannot override those set by the operator itself. For example if I want to add EXTRA_OPTS and  SERVER_JVMFLAGS to the config-spec I do this:

    envOverrides:
      EXTRA_OPTS: "foobarbaz"
      SERVER_JVMFLAGS: "-Dzookeeper.4lw.commands.whitelist=* -Xmx1000m"

When I check the process's environment I can see that EXTRA_OPTS has been set, but SERVER_JVMFLAGS has been overridden.

    EXTRA_OPTS=foobarbaz
    SERVER_JVMFLAGS=-Xmx1000m -javaagent:/stackable/jmx/jmx_prometheus_javaagent-0.16.1.jar=9505:/stackable/jmx/server.yaml

The config-spec environment variable overrides should reflect in the environment used by ZooKeeper at runtime.

**Comment by maltesander** [comment]
Yeah that is set when we use monitoring (and no checks are done, just overwritten). We should think of a smarter way on how to enable that.

**Comment by teozkr** [comment]
This is now flipped as of #263, so that an `envOverride` of `SERVER_JVMFLAGS` completely replaces the injected prometheus agent.

Not super happy with that either, but at least it's in the spirit of all other overrides we support...

**Comment by teozkr** [comment]
@Jimvin feel free to reopen if you disagree with that assessment.
