### ISSUE TITLE
Operator creates endless pods

### ISSUE THREAD

**Issue by hikhvar** [stackabletech/zookeeper-operator#297]
Hello, 
I can reproduce this with the `0.6.0` stable chart.
As soon as you create a `zookeepercluster` with more than a single node, the operator will delete and recreate pods over and over in a thight loop. This results in thousands of pods in terminating state. 
My observation:
* The configmaps are created in the default namespace
* The pods are created in the namespace the operator is running in

A quick glance in the code shows that there are two different sources are used for the namespace of the resources:
Configmap:
https://github.com/stackabletech/zookeeper-operator/blob/0.6.0/rust/operator/src/lib.rs#L314
Pod:
https://github.com/stackabletech/zookeeper-operator/blob/0.6.0/rust/operator/src/lib.rs#L486

I run the stackable-operator in a namespace different from `default`.

**Comment by lfrancke** [comment]
This is a critical issue and I'll put it on the list but I'm not sure if it's going to be relevant after the rework.

**Comment by hikhvar** [comment]
If I deploy the Operator in the default namespace, everything works as expected.

**Comment by soenkeliebau** [comment]
Hi @hikhvar - you are indeed correct, this is not the way it should be.
We are on the verge of merging the "new" Zookeeper operator, which should hopefully not exhibit this behavior, would it be acceptable to wait until maybe Friday and test with this?

**Comment by hikhvar** [comment]
Yes totally acceptable. We implented the workaround already.

**Comment by soenkeliebau** [comment]
alright, thank you, so I'll close this here.
