### ISSUE TITLE
ZooKeeper pods don't have zookeeper prepended to the pod name

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/zookeeper-operator#333]
Stackable operators usually prepend the service name to the pod name, but the ZooKeeper operator doesn't do this. Deploying a single-node ZooKeeper service creates a pod named "simple-server-default-0" when the expected name would be something like "zookeeper-simple-server-default-0". This is the observed behaviour of other Stackable operators.

**Comment by teozkr** [comment]
Closing this, since we're moving away from supporting name conflicts between clusters.
