### ISSUE TITLE
ZooKeeper 3.6/3.7 support

### ISSUE THREAD

**Issue by teozkr** [stackabletech/zookeeper-operator#368]
Looks like there is discussion of retiring 3.5 maintenance upstream, so this is becoming a bit more urgent: https://lists.apache.org/thread/p9hrym3jb093lqrv568bhh68wr4vyon9

**Comment by maltesander** [comment]
@teozkr we support 3.6 and 3.7, can this be closed?

**Comment by teozkr** [comment]
Yes.
