### ISSUE TITLE
OpenShift Certification Step 2: Certify the Operator

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/zookeeper-operator#486]
This is done when the ZooKeeper Operator has been successfully certified against OpenShift (the technical precertifcation only).

For now this can be done in a manual way.
It is important to create follow-up tickets to capture required changes to other operators and to identify which steps could in theory be automated in the future.

**Comment by lfrancke** [comment]
Razvan to create sub-tickets. When this is done we can prioritize those.

**Comment by razvan** [comment]
The ZK operator is now OS certified.
