### ISSUE TITLE
Document myidOffset

### ISSUE THREAD

**Issue by teozkr** [stackabletech/zookeeper-operator#557]
### Problem

The cluster is unable to start when running multiple rolegroups without setting `myidOffset`, see https://github.com/stackabletech/zookeeper-operator/issues/546.

The property exists in the CRDs, but doesn't seem to be documented anywhere.

### Solution

Document that `myidOffset` must be set when running multiple rolegroups.

This should be in the Usage. We also want to use the opportunity to split the usage page into multiple pages, like it is done for trino: https://docs.stackable.tech/trino/stable/usage_guide/index.html

Then there'd be a new page "Running multiple role groups" where it would document that you have to set the myIdOffset

### Acceptance Criteria
- [ ] usage page split up
- [ ] new page "Running multiple role groups" created that documents setting the property

**Comment by lfrancke** [comment]
This is currently not caught in the operator at all, right?

**Comment by maltesander** [comment]
No just exists in an example i think.
