### ISSUE TITLE
Document operator system requirements

### ISSUE THREAD

**Issue by maltesander** [stackabletech/zookeeper-operator#559]
We want to document user-_guidelines_ for the operator in terms of e.g. min/max CPU, memory and disk space. These are **non-binding** (as an accurate assessment is dependent on a specific use-case) but may be referred to from GTCs and other contract documents. 

This should be documented as described in https://github.com/stackabletech/documentation/issues/289

## Acceptance

- [x] run the following
  - [x] zookeeper operator managing single ZK instance (serving HDFS, HBase and Kafka clusters)
  - [x] zookeeper operator managing multiple ZK instances in different namespaces (each serving HDFS, HBase and Kafka clusters)
  - [x] vary cluster sizes 
- [x] recommendations for CPU, memory and disk space per zookeeper instance managed by the operator, for
  - [x] Kind cluster 
  - [x] Managed k8s cluster (at least one)
- [x] The results are added to a table in the documentation as described in https://github.com/stackabletech/documentation/issues/289

**Comment by lfrancke** [comment]
Thank you, this looks good.
Is there any reason to believe we need to test every operator or can we assume that we can copy the requirements from one to the other?

Especially as this will potentially change with every new PR?

I would suggest we do one, double or quadruple the memory and disk space required and set that as the minimum.

What do you think?

**Comment by adwk67** [comment]
> Thank you, this looks good. Is there any reason to believe we need to test every operator or can we assume that we can copy the requirements from one to the other?
> 
> Especially as this will potentially change with every new PR?
> 
> I would suggest we do one, double or quadruple the memory and disk space required and set that as the minimum.
> 
> What do you think?

I think that makes sense: we could look at this one (zookeeper) in some detail (as it will typically serve multiple product clusters) and then use that as rule-of-thumb benchmark.

**Comment by adwk67** [comment]
#### Results with zookeeper (and hdfs) operator(s)

##### 1. Kind cluster

- Scenario
  - run multiple Zookeeper and HDFS clusters in different namespaces (tested with 3, 10 and 30 namespaces)
  - laptop: 8 cores and 48 GB RAM
  - zookeeper server configured for 0.5GB RAM and between 0.25 and 0.5 CPUs
  - hdfs configured with 2 NNs, 1 DN, 1 JN
- Observations
  - operator footprint remains steady and small
    - zookeeper max.: 0.13 cores, 35 MB
    - hdfs max.: 0.1 cores, 23 MB
  - this is the case even when the cluster is under 99% CPU usage: the zookeeper operator can delete and apply a cluster in 30 namespaces without any noticeable spike
  - limits are thus determined by product dimensions/usage, and not operators
- Recommendations
  - operator overhead: at least **0.2 cores** and **100MB RAM** per operator (or a multiple thereof to be on the safe side)
  - this matches well with @fhennig's [notes](https://github.com/stackabletech/documentation/issues/247#issue-1319312157)

**Comment by adwk67** [comment]
##### 2. Managed k8s (AWS 1.22)

- Scenario
  - run multiple Zookeeper and HDFS clusters in different namespaces (tested with 3 and 30 namespaces)
  - 3 nodes: each with approx 2 cores and 8 GB RAM
  - zookeeper server configured for 0.5GB RAM and between 0.25 and 0.5 CPUs (as above for kind)
  - hdfs configured with 2 NNs, 1 DN, 1 JN (as above for kind)
- Observations
  - operator footprint remains steady and small
    - zookeeper max.: 0.05 cores, 21 MB
    - hdfs: cluster size prevented hdfs from being spun up as CPU was at its limit
  - zookeeper alone (no hdfs): the zookeeper operator can delete and apply a cluster in 30 namespaces without any noticeable spike
  - limits are thus determined by product dimensions/usage, and not operators
- Recommendations
  - as above (for kind)

**Comment by lfrancke** [comment]
Awesome, thank you!
Those results look pretty good but not unexpected.

How about we say 1 core and 256 GB of RAM per operator?
Or is that too much?

**Comment by maltesander** [comment]
I think one core is too much. That would reserve like 10 cores for the SDP just for the operators. I think 0.1 or 0.2 cores should be sufficient. Memory 256 MB sounds ok, i think we still go down to 128MB here as well.

**Comment by adwk67** [comment]
> I think one core is too much. That would reserve like 10 cores for the SDP just for the operators. I think 0.1 or 0.2 cores should be sufficient. Memory 256 MB sounds ok, i think we still go down to 128MB here as well.

I agree - I think 0.2 cores + 256 MB RAM should be fine if we word it appropriately e.g. something like "Resource sizing depends on cluster type(s), usage and scope, but as a starting point we recommend a minimum of ... per operator"

**Comment by teozkr** [comment]
I'm not sure talking about "N cores" is useful without at least having some reference for what cores we've tested against (not that this has to be super exhaustive but at least giving some kind of frame of reference). 0.2 sandy bridge cores is going to give you very different results from either 0.2 zen 4 cores or 0.2 Cortex-M0 cores.

**Comment by lfrancke** [comment]
Giving any core recommendations always feels weird either way. It should work as long as it gets any CPU cycles....
But I agree - we could at least put a reference in there and never change that. Andrew's laptop specs will be enshrined in the docs.

**Comment by adwk67** [comment]
@lfrancke We can use the same text for all operators, I would say, even if it is a little redundant. That way, we can make things operator-specific at a later stage without moving docs-stuff around. Do we need an epic for that, or just a bunch of individual issues?

**Comment by lfrancke** [comment]
We already have an epic for that: https://github.com/stackabletech/documentation/issues/289

I can either create subtasks in there or we just pull in that whole epic and just tick the individual boxes one by one/link them to the relevant PRs.
What do you prefer?

**Comment by adwk67** [comment]
Just one epic with tick boxes, as the change is trivial.

**Comment by lfrancke** [comment]
I've added the issue to the board in the "Next" column
