### ISSUE TITLE
ZNode reconciliation sometimes gets stuck

### ISSUE THREAD

**Issue by teozkr** [stackabletech/zookeeper-operator#567]
### Affected version

0.11.0

### Current and expected behavior

Sometimes the ZNode deployment gets "stuck" when deployed at the same time as the ZookeeperCluster. No discovery configmap is produced, and no events are created to alert the operator about what's happening.

Restarting zookeeper-operator seems to loosen whatever was going wrong and quickly creates the CM.

Ideally either the CM should be created or an event logged within a reasonable timeframe (let's say 5s or so).

### Possible solution

1. Add a timeout to the ZNode provisioner
2. Figure out why it isn't able to connect as soon as the ZK cluster is available

### Environment

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.11", GitCommit:"dc2898b20c6bd9602ae1c3b51333e2e4640ed249", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+k3s1", GitCommit:"313aaca547f030752788dce696fdf8c9568bc035", GitTreeState:"clean", BuildDate:"2022-03-31T01:02:40Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

### Would you like to work on fixing this bug?

yes

**Comment by maltesander** [comment]
I could not reproduce this.

Sometimes the operator produces an error like this:
```
2022-12-14T16:41:44.820729Z ERROR stackable_operator::logging::controller: Failed to reconcile object controller.name="znode.zookeeper.stackable.tech" error=reconciler for object ZookeeperZnode.v1alpha1.zookeeper.stackable.tech/simple-znode.default failed error.sources=[failed to ensure that ZNode /znode-68bb302d-58c3-4b41-a35e-e3fc4cc420be exists in ZookeeperCluster.v1alpha1.zookeeper.stackable.tech/simple-zk.default, invalid address simple-zk.default
.svc.cluster.local:2181, failed to lookup address information: Name or service not known]
```

The discovery config map however was always created. The nodeport service `simple-zk.default
.svc.cluster.local:2181` is reachable (and existed) from the operator pod.

I feel this is some weird DNS / timeout problem.
