### ISSUE TITLE
Rework: ZooKeeper (split encryption and authentication according to the decision)

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/zookeeper-operator#596]
See https://github.com/stackabletech/issues/issues/293 for details

**Comment by maltesander** [comment]
To avoid huge merge conflicts and not make @siegfriedweber go crazy, i would wait for this first: https://github.com/stackabletech/zookeeper-operator/pull/588

**Comment by lfrancke** [comment]
This included a CRD change, correct?

**Comment by lfrancke** [comment]
Ignore me, I see that the labels are on the PR
