### ISSUE TITLE
Document new discovery CM property for the PORT

### ISSUE THREAD

**Issue by fhennig** [stackabletech/zookeeper-operator#677]
- document that it exists (here: https://docs.stackable.tech/home/stable/zookeeper/discovery.html#_contents)
- document that both the individual port and the full connection string need to be provided and kept in sync

context from the arch meeting:

> One concern: What if the Port in one key goes out of sync with the other key? What if we switch pulling the port from one key to the other key? Is that a breaking change? (In HBase for example)
> 
> Solution: Our operator already keeps these properties in sync, and we specifiy that they need to be in sync. If a user writes their own CM, they are responsible for providing all the keys and keeping them in sync. Switching where the port gets read from is an implementation detail and changing it is not a breaking change.

**Comment by maltesander** [comment]
> * document that both the individual port and the full connection string need to be provided and kept in sync

I think thats a no brainer but documenting it doesnt hurt.

I think whats rather more interesting is documenting what fields each operator, depending on ZooKeeper, reads. For some the full connection string with ZNode and port are enough, Some need only connection string with separate ZNode etc.
(This would be in each product depending on ZooKeeper or other discovery mechanisms, but that is probably out of scope as well).

**Comment by fhennig** [comment]
Yes this is what we were also talking about in the Arch meeting. We should probably document it. But also we don't want it to be a breaking change if we change anything, is what @nightkr was saying.
