### ISSUE TITLE
Allow k8s administrators to override ZNode path

### ISSUE THREAD

**Issue by nightkr** [stackabletech/zookeeper-operator#681]
This is currently not allowed because it would let users escalate "Is allowed to create sandboxed ZNodes" to "Is allowed to take ownership of any named ZNode".

However, this is preventing users from restoring failed clusters from backups, since there is no way to influence the UID generation at all. One possible compromise would be to introduce a new field `ZookeeperZnode.status.znodePath`, which defaults to `/{uid}`. This would let administrators status-patch the object to override the path, while regular users are typically prohibited (by K8s) from editing the status subresource.

**Comment by sbernauer** [comment]
LGTM

**Comment by nightkr** [comment]
Moving this into the voting phase.

**Comment by nightkr** [comment]
No dissent, considering this _accepted_.

**Comment by sbernauer** [comment]
Is this already implemented? https://github.com/stackabletech/zookeeper-operator/pull/799 looks like the implementation and is not merged yet

**Comment by lfrancke** [comment]
I don't know. I found this in the `Done` column

**Comment by nightkr** [comment]
Not sure how this got moved to done, #799 has indeed not been reviewed yet.

> Is this anything we documented?

It's documented in the PR, but since that still hasn't been merged...

**Comment by lfrancke** [comment]
As this has been merged now, can you please include a link to the generated docs?

**Comment by nightkr** [comment]
@lfrancke https://docs.stackable.tech/home/nightly/zookeeper/usage_guide/isolating_clients_with_znodes#_restoring_from_backups
