### ISSUE TITLE
Documentation doesn't mention StorageClass override

### ISSUE THREAD

**Issue by nightkr** [stackabletech/zookeeper-operator#687]
See https://github.com/orgs/stackabletech/discussions/22#discussioncomment-5976327

The CRDs support it, but https://docs.stackable.tech/home/stable/zookeeper/usage_guide/resource_configuration.html doesn't mention it.

**Comment by fhennig** [comment]
I want to document this in the overall concepts docs: https://github.com/stackabletech/documentation/pull/441

And then link to there from the ZK docs

**Comment by fhennig** [comment]
fixed: https://github.com/stackabletech/zookeeper-operator/pull/718
