### ISSUE TITLE
Vector aggregator discovery config path not consistent with other Stackable operators

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/zookeeper-operator#736]
### Affected version

23.7.0

### Current and expected behavior

The ZooKeeper operator uses the property clusterConfig.logging.vectorAggregatorConfigMapName for Vector aggregator discovery whereas the other operators use clusterConfig.vectorAggregatorConfigMapName. In ZooKeeper it is configured like this:

```
  clusterConfig:
    logging:
      vectorAggregatorConfigMapName: vector-aggregator-discovery
```

For consistency with other operators it should be expressed like this:

```
  clusterConfig:
    vectorAggregatorConfigMapName: vector-aggregator-discovery
```

### Would you like to work on fixing this bug?

None

**Comment by fhennig** [comment]
Oh damn! that's important to me, we should fix this asap
