### ISSUE TITLE
ConfigOverrides not working properly

### ISSUE THREAD

**Issue by maltesander** [stackabletech/zookeeper-operator#761]
ConfigOverrides are not working correctly in https://github.com/stackabletech/zookeeper-operator/blob/bb9d6fa638b02d743cdf8fbf58a729048d90cb21/rust/operator-binary/src/zk_controller.rs#L539

We need to make sure to extend the config files with the merged role / rolegroup config as the last step before writing out the data.

**Comment by lfrancke** [comment]
@soenkeliebau Do we have a similar problem with env vars or not?

**Comment by soenkeliebau** [comment]
As far as I can tell env overrides work as intended.
ZooKeeper just prioritizes the config file over system properties internally.
